#!/bin/bash
# scripts/wrap-up.sh - Automated session wrap-up

SESSION_DATE=$(date '+%Y-%m-%d')
SESSION_DIR="docs/sessions/$SESSION_DATE"

echo "=== Session Wrap-Up for $SESSION_DATE ==="

# Create session directory
mkdir -p "$SESSION_DIR"

# Generate wrap-up template
cat > "$SESSION_DIR/wrap-up.md" << EOF
# Session Wrap-Up - $SESSION_DATE

## Summary
[Generated by script, to be filled by LLM]

## Metrics
- Files Modified: $(git status --porcelain | wc -l)
- Lines Changed: $(git diff --stat | tail -1)
- Features Touched: [To be filled]

## Next Session
- [ ] Priority 1:
- [ ] Priority 2:
- [ ] Priority 3:
EOF

echo "✓ Session directory created"
echo "✓ Please complete the wrap-up documentation"
echo "✓ Don't forget to commit and push!"
